name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true


flutter_native_splash:
  color: "#F19A0D"
  image: assets/splash/Splachscreen.png

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/splash/logo.png'